
global proc install_module()
{
	global string $gShelfTopLevel;
	string $currentShelf = `tabLayout -query -selectTab $gShelfTopLevel`;
	setParent $currentShelf;
	string $icon_prefix = "png";
	string $asInstallScriptLocation=`asInstallScriptLocation`;

	string $script_name = "Custom_Vertex_Color";

	string $source_file = $asInstallScriptLocation+$script_name+".py";

	string $icon2 = $asInstallScriptLocation+"/icon/Custom_Vertex_Color_icon."+$icon_prefix;

	string $maya_version[] = stringToStringArray(`about -v`, " ");

	string $import_base_text = "import os\nimport sys\nsys.path.append('"+$asInstallScriptLocation+"')\n";

   	string $command_name = $import_base_text + "import Custom_Vertex_Color as CVC\nimport importlib\nimportlib.reload(CVC)\nmain_window = CVC.show_main_window()";

	if (!`file -q -ex $source_file`)
	{
		error ("Something went wrong, can not find: \""+$source_file+"\"");
	}

	shelfButton
		-command $command_name
		-annotation $script_name
		-label $script_name
		-image $icon2
		-image1 $icon2
		-sourceType "python";

	string $osTypeFile;
	string $operatingSystem = `about -os`;
	if ($operatingSystem == "win64") 
	{
		$osTypeFile = "py";
	}

	string $srcWindows=$asInstallScriptLocation;
	string $version = `about -environmentFile`;
	string $verPath =`substring $version 1 (size($version)-8)`;
	string $destWindows=$verPath;
	sysFile -makeDir ($verPath);
	sysFile -copy $destWindows $srcWindows;

	print ("\n// "+ $maya_version[0] + " is the current MAYA version.\n");
	print ("\n// "+ $script_name + " has been added to current shelf.\n");
}

global proc as_install_script_locator ()
{
}

global proc string asInstallScriptLocation ()
{
	string $whatIs = `whatIs as_install_script_locator`;
	string $fullPath = `substring $whatIs 25 999`;
	string $buffer[];
	int $numTok = `tokenize $fullPath "/" $buffer`;
	int $numLetters = size($fullPath);
	int $numLettersLastFolder = size($buffer[$numTok-1]);
	string $scriptLocation = `substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
	return $scriptLocation;
}
install_module;

