SET MAYA_UI_LANGUAGE=ja_JP
SET PYTHONPATH=C:\Users\waltz\Documents\MAYA_Module\Maya_Modules\Misc\HIK

SET MAYA_CMD_FILE_OUTPUT=C:\Users\waltz\Documents\Maya_Project\Redemption_Assets\Downloaded\DHI\aue9PLqF_asset\8k\asset_source\MetaHumans\Animations\Traversal\Log\M_Neutral_Traversal_Climb_Start_2_5_stand_F_Lfoot.log
"C:\Program Files\Autodesk\Maya2023\bin\mayabatch.exe" -command "python(\"import HIK_Automation;HIK_Automation.run('C:/Users/waltz/Documents/Maya_Project/Redemption_Assets/Downloaded/DHI/aue9PLqF_asset/8k/asset_source/MetaHumans/Animations/Traversal/M_Neutral_Traversal_Climb_Start_2_5_stand_F_Lfoot.FBX')\")"
SET MAYA_CMD_FILE_OUTPUT=C:\Users\waltz\Documents\Maya_Project\Redemption_Assets\Downloaded\DHI\aue9PLqF_asset\8k\asset_source\MetaHumans\Animations\Traversal\Log\M_Neutral_Traversal_Climb_Start_2_5_stand_F_Rfoot.log
"C:\Program Files\Autodesk\Maya2023\bin\mayabatch.exe" -command "python(\"import HIK_Automation;HIK_Automation.run('C:/Users/waltz/Documents/Maya_Project/Redemption_Assets/Downloaded/DHI/aue9PLqF_asset/8k/asset_source/MetaHumans/Animations/Traversal/M_Neutral_Traversal_Climb_Start_2_5_stand_F_Rfoot.FBX')\")"
SET MAYA_CMD_FILE_OUTPUT=C:\Users\waltz\Documents\Maya_Project\Redemption_Assets\Downloaded\DHI\aue9PLqF_asset\8k\asset_source\MetaHumans\Animations\Traversal\Log\M_Neutral_Traversal_Mantle_1_0_stand_F_Lfoot.log
"C:\Program Files\Autodesk\Maya2023\bin\mayabatch.exe" -command "python(\"import HIK_Automation;HIK_Automation.run('C:/Users/waltz/Documents/Maya_Project/Redemption_Assets/Downloaded/DHI/aue9PLqF_asset/8k/asset_source/MetaHumans/Animations/Traversal/M_Neutral_Traversal_Mantle_1_0_stand_F_Lfoot.FBX')\")"
SET MAYA_CMD_FILE_OUTPUT=C:\Users\waltz\Documents\Maya_Project\Redemption_Assets\Downloaded\DHI\aue9PLqF_asset\8k\asset_source\MetaHumans\Animations\Traversal\Log\M_Neutral_Traversal_Mantle_1_0_stand_F_Rfoot.log
"C:\Program Files\Autodesk\Maya2023\bin\mayabatch.exe" -command "python(\"import HIK_Automation;HIK_Automation.run('C:/Users/waltz/Documents/Maya_Project/Redemption_Assets/Downloaded/DHI/aue9PLqF_asset/8k/asset_source/MetaHumans/Animations/Traversal/M_Neutral_Traversal_Mantle_1_0_stand_F_Rfoot.FBX')\")"